"""Location Not Null

Revision ID: 1fcde34457e5
Revises: ebd03e21c571
Create Date: 2025-03-20 01:32:52.526401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '1fcde34457e5'
down_revision: Union[str, None] = 'ebd03e21c571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('location', 'geom',
               existing_type=Geometry(geometry_type='POINT', srid=3035, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('location', 'geom',
               existing_type=Geometry(geometry_type='POINT', srid=3035, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               nullable=True)
    # ### end Alembic commands ###
